### ISSUE TITLE
Different hash values every time for the same string

### ISSUE THREAD

**Issue by daniel-lahoz** [attaswift/SipHash#4]
I had detect a problem with the hasher, every time I execute them I get a different hash for the same exact string:

My simply test code:

> var hasherTest = SipHasher()
> hasherTest.append("Test")
> let hashVal = hasherTest.finalize()

I run one time:
> Printing description of hashVal:
434885335948154737

Then I run again:
> Printing description of hashVal:
-3387410001051536137

And so on, the hash value is always different, happend on Device and Simulator.

If I use several hashers in the same execution, then I get the same value, but when I run the code again, values are not the same than in the previous execution.

I am using version 1.2.

**Comment by lorentey** [comment]
This is very much intentional; random seeding is an important part of SipHash, and `Hashable` in the stdlib is explicitly documented to allow it.
